/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar;

/**
 *
 * @author Cielo
 */
public class VENTANA extends javax.swing.JFrame {

    /**
     * Creates new form VENTANA
     */
    public VENTANA() {
        initComponents();
        Cliente.setBounds(0, 0, 0, 0);        
        Empleado.setBounds(0, 0, 0, 0); 
        Proyecto.setBounds(0, 0, 0, 0); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CerrarSesion = new javax.swing.JButton();
        botonProyecto = new javax.swing.JButton();
        botonEmpleado = new javax.swing.JButton();
        botonCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PintarNombreUsuario = new javax.swing.JLabel();
        Proyecto = new javax.swing.JPanel();
        NombreProyecto = new javax.swing.JTextField();
        CodigoProyecto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        TipoProyecto = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        GuardarProyecto = new javax.swing.JButton();
        MostrarProyecto = new javax.swing.JButton();
        NuevoProyecto = new javax.swing.JButton();
        EliminarProyecto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Empleado = new javax.swing.JPanel();
        IDEmpleado = new javax.swing.JTextField();
        Nomina = new javax.swing.JTextField();
        TelefonoEmpleado = new javax.swing.JTextField();
        CorreoEmpleado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        NombreEmpleado = new javax.swing.JTextField();
        ProyectosRealizadosEmpleados = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ProyectosRealizadossCheck = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        GuardarEmpleado = new javax.swing.JButton();
        MostrarEmpleado = new javax.swing.JButton();
        NuevoEmpleado = new javax.swing.JButton();
        EliminarEmpleado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        Jefe = new javax.swing.JCheckBox();
        Cliente = new javax.swing.JPanel();
        RadioButtonPersona = new javax.swing.JRadioButton();
        RadioButtonEmpresa = new javax.swing.JRadioButton();
        ID = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Correo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Tipo = new javax.swing.JTextField();
        AporteFinanciero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AporteFinCheck = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        GuardarCliente = new javax.swing.JButton();
        MostarCliente = new javax.swing.JButton();
        NuevoCliente = new javax.swing.JButton();
        EliminarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arquitectos Movimientos");
        setMinimumSize(new java.awt.Dimension(1021, 540));
        setPreferredSize(new java.awt.Dimension(1001, 501));
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);

        CerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        CerrarSesion.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        CerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setText("Cerrar sesión");
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });

        botonProyecto.setBackground(new java.awt.Color(0, 0, 0));
        botonProyecto.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        botonProyecto.setForeground(new java.awt.Color(255, 255, 255));
        botonProyecto.setText("Proyecto");
        botonProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProyectoActionPerformed(evt);
            }
        });

        botonEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        botonEmpleado.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        botonEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        botonEmpleado.setText("Empleado");
        botonEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEmpleadoActionPerformed(evt);
            }
        });

        botonCliente.setBackground(new java.awt.Color(0, 0, 0));
        botonCliente.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        botonCliente.setForeground(new java.awt.Color(255, 255, 255));
        botonCliente.setText("Cliente");
        botonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario Nombre Ejemplo");

        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU");

        PintarNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        PintarNombreUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(botonCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2)))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(PintarNombreUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PintarNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(botonCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(CerrarSesion)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 20, 230, 460);

        Proyecto.setBackground(new java.awt.Color(153, 153, 153));
        Proyecto.setMinimumSize(new java.awt.Dimension(629, 400));

        NombreProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreProyectoActionPerformed(evt);
            }
        });

        CodigoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoProyectoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel13.setText("NOMBRE: ");

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel14.setText("CODIGO:");

        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel15.setText("TIPO:");

        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });

        TipoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoProyectoActionPerformed(evt);
            }
        });

        jCheckBox2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jCheckBox2.setText("PRESUPUESTO");
        jCheckBox2.setOpaque(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel17.setText("Registro de todos los proyectos");

        GuardarProyecto.setBackground(new java.awt.Color(0, 0, 0));
        GuardarProyecto.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        GuardarProyecto.setForeground(new java.awt.Color(255, 255, 255));
        GuardarProyecto.setText("Guardar");
        GuardarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProyectoActionPerformed(evt);
            }
        });

        MostrarProyecto.setBackground(new java.awt.Color(0, 0, 0));
        MostrarProyecto.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        MostrarProyecto.setForeground(new java.awt.Color(255, 255, 255));
        MostrarProyecto.setText("Mostrar");
        MostrarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarProyectoActionPerformed(evt);
            }
        });

        NuevoProyecto.setBackground(new java.awt.Color(0, 0, 0));
        NuevoProyecto.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NuevoProyecto.setForeground(new java.awt.Color(255, 255, 255));
        NuevoProyecto.setText("Nuevo");
        NuevoProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoProyectoActionPerformed(evt);
            }
        });

        EliminarProyecto.setBackground(new java.awt.Color(0, 0, 0));
        EliminarProyecto.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        EliminarProyecto.setForeground(new java.awt.Color(255, 255, 255));
        EliminarProyecto.setText("Eliminar");
        EliminarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarProyectoActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Registro", "Codigo", "Presupuesto", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(3).setHeaderValue("Nombre");
        }

        javax.swing.GroupLayout ProyectoLayout = new javax.swing.GroupLayout(Proyecto);
        Proyecto.setLayout(ProyectoLayout);
        ProyectoLayout.setHorizontalGroup(
            ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProyectoLayout.createSequentialGroup()
                .addGroup(ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProyectoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(TipoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ProyectoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ProyectoLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jCheckBox2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProyectoLayout.createSequentialGroup()
                        .addGroup(ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MostrarProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NuevoProyecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProyectoLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProyectoLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(108, 108, 108))))
        );
        ProyectoLayout.setVerticalGroup(
            ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProyectoLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(MostrarProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarProyecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NuevoProyecto)
                .addGap(10, 10, 10)
                .addComponent(GuardarProyecto)
                .addGap(11, 11, 11))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProyectoLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addGroup(ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(NombreProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CodigoProyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProyectoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TipoProyecto)
                .addContainerGap())
        );

        getContentPane().add(Proyecto);
        Proyecto.setBounds(510, 80, 230, 400);

        Empleado.setBackground(new java.awt.Color(153, 153, 153));
        Empleado.setMinimumSize(new java.awt.Dimension(629, 400));

        IDEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEmpleadoActionPerformed(evt);
            }
        });

        Nomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NominaActionPerformed(evt);
            }
        });

        TelefonoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoEmpleadoActionPerformed(evt);
            }
        });

        CorreoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoEmpleadoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel19.setText("ID: ");

        jLabel20.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel20.setText("NOMINA: ");

        jLabel21.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel21.setText("TELEFONO:");

        jLabel22.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel22.setText("NOMBRE:");

        NombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreEmpleadoActionPerformed(evt);
            }
        });

        ProyectosRealizadosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProyectosRealizadosEmpleadosActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel23.setText("CORREO:");

        ProyectosRealizadossCheck.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        ProyectosRealizadossCheck.setText("PROYECTOS REALIZADOS");
        ProyectosRealizadossCheck.setOpaque(false);
        ProyectosRealizadossCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProyectosRealizadossCheckActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel24.setText("Registro de todos los empleados");

        GuardarEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        GuardarEmpleado.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        GuardarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        GuardarEmpleado.setText("Guardar");
        GuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarEmpleadoActionPerformed(evt);
            }
        });

        MostrarEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        MostrarEmpleado.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        MostrarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        MostrarEmpleado.setText("Mostrar");
        MostrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarEmpleadoActionPerformed(evt);
            }
        });

        NuevoEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        NuevoEmpleado.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NuevoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        NuevoEmpleado.setText("Nuevo");
        NuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoEmpleadoActionPerformed(evt);
            }
        });

        EliminarEmpleado.setBackground(new java.awt.Color(0, 0, 0));
        EliminarEmpleado.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        EliminarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        EliminarEmpleado.setText("Eliminar");
        EliminarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarEmpleadoActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Registro", "Nomina", "Telefono", "Nombre", "Correo"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        Jefe.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        Jefe.setText("JEFE");
        Jefe.setOpaque(false);
        Jefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JefeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmpleadoLayout = new javax.swing.GroupLayout(Empleado);
        Empleado.setLayout(EmpleadoLayout);
        EmpleadoLayout.setHorizontalGroup(
            EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpleadoLayout.createSequentialGroup()
                .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmpleadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ProyectosRealizadosEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpleadoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jefe)
                        .addGap(18, 18, 18)
                        .addComponent(ProyectosRealizadossCheck))
                    .addGroup(EmpleadoLayout.createSequentialGroup()
                        .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmpleadoLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpleadoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CorreoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EmpleadoLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(IDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpleadoLayout.createSequentialGroup()
                        .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MostrarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NuevoEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpleadoLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmpleadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(108, 108, 108))
        );
        EmpleadoLayout.setVerticalGroup(
            EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpleadoLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(IDEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Nomina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(TelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(NombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CorreoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(EmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProyectosRealizadossCheck)
                    .addComponent(Jefe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ProyectosRealizadosEmpleados)
                .addContainerGap())
            .addGroup(EmpleadoLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(MostrarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NuevoEmpleado)
                .addGap(10, 10, 10)
                .addComponent(GuardarEmpleado)
                .addGap(11, 11, 11))
        );

        getContentPane().add(Empleado);
        Empleado.setBounds(750, 80, 230, 400);

        Cliente.setBackground(new java.awt.Color(153, 153, 153));
        Cliente.setMinimumSize(new java.awt.Dimension(629, 400));

        RadioButtonPersona.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        RadioButtonPersona.setText("Persona");
        RadioButtonPersona.setOpaque(false);

        RadioButtonEmpresa.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        RadioButtonEmpresa.setText("Empresa");
        RadioButtonEmpresa.setOpaque(false);

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });

        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel5.setText("ID: ");

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel6.setText("NOMBRE: ");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel7.setText("TELEFONO:");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel8.setText("TIPO:");

        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });

        AporteFinanciero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AporteFinancieroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel9.setText("CORREO:");

        AporteFinCheck.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        AporteFinCheck.setText("APORTE FINANCIERO");
        AporteFinCheck.setOpaque(false);
        AporteFinCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AporteFinCheckActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel10.setText("Registro de todos los clientes");

        GuardarCliente.setBackground(new java.awt.Color(0, 0, 0));
        GuardarCliente.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        GuardarCliente.setForeground(new java.awt.Color(255, 255, 255));
        GuardarCliente.setText("Guardar");
        GuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarClienteActionPerformed(evt);
            }
        });

        MostarCliente.setBackground(new java.awt.Color(0, 0, 0));
        MostarCliente.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        MostarCliente.setForeground(new java.awt.Color(255, 255, 255));
        MostarCliente.setText("Mostrar");
        MostarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostarClienteActionPerformed(evt);
            }
        });

        NuevoCliente.setBackground(new java.awt.Color(0, 0, 0));
        NuevoCliente.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        NuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        NuevoCliente.setText("Nuevo");
        NuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoClienteActionPerformed(evt);
            }
        });

        EliminarCliente.setBackground(new java.awt.Color(0, 0, 0));
        EliminarCliente.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        EliminarCliente.setForeground(new java.awt.Color(255, 255, 255));
        EliminarCliente.setText("Eliminar");
        EliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClienteActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Registro", "ID", "Nombre", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Nombre");
        }

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel11.setText("EL CLIENTE ES: ");

        javax.swing.GroupLayout ClienteLayout = new javax.swing.GroupLayout(Cliente);
        Cliente.setLayout(ClienteLayout);
        ClienteLayout.setHorizontalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(AporteFinanciero, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(AporteFinCheck))
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ClienteLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClienteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClienteLayout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(RadioButtonPersona)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RadioButtonEmpresa))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ClienteLayout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClienteLayout.createSequentialGroup()
                        .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MostarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EliminarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GuardarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NuevoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClienteLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(108, 108, 108))
            .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClienteLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel11)
                    .addContainerGap(523, Short.MAX_VALUE)))
        );
        ClienteLayout.setVerticalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioButtonEmpresa)
                    .addComponent(RadioButtonPersona))
                .addGap(18, 18, 18)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AporteFinCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AporteFinanciero)
                .addContainerGap())
            .addGroup(ClienteLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(MostarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NuevoCliente)
                .addGap(10, 10, 10)
                .addComponent(GuardarCliente)
                .addGap(11, 11, 11))
            .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ClienteLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jLabel11)
                    .addContainerGap(322, Short.MAX_VALUE)))
        );

        getContentPane().add(Cliente);
        Cliente.setBounds(270, 80, 230, 400);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1001, 501);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProyectoActionPerformed
        
        Cliente.setVisible(false);
        Empleado.setVisible(false);
        Proyecto.setBounds(270, 80, 629, 400);
        Proyecto.setVisible(true);
    }//GEN-LAST:event_botonProyectoActionPerformed

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        PANTALLAuser pan = new PANTALLAuser();
        pan.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void botonEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEmpleadoActionPerformed
       
        Cliente.setVisible(false);
        Empleado.setBounds(270, 80, 629, 400);
        Empleado.setVisible(true);
        Proyecto.setVisible(false);
    }//GEN-LAST:event_botonEmpleadoActionPerformed

    private void botonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteActionPerformed
        Cliente.setBounds(270, 80, 629, 400);
        Cliente.setVisible(true);
        Empleado.setVisible(false);
        Proyecto.setVisible(false);
    }//GEN-LAST:event_botonClienteActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoActionPerformed

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    private void AporteFinancieroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AporteFinancieroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AporteFinancieroActionPerformed

    private void AporteFinCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AporteFinCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AporteFinCheckActionPerformed

    private void GuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarClienteActionPerformed

    private void MostarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostarClienteActionPerformed

    private void NuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoClienteActionPerformed

    private void EliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarClienteActionPerformed

    private void NombreProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreProyectoActionPerformed

    private void CodigoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoProyectoActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void TipoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoProyectoActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void GuardarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarProyectoActionPerformed

    private void MostrarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarProyectoActionPerformed

    private void NuevoProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoProyectoActionPerformed

    private void EliminarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarProyectoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarProyectoActionPerformed

    private void IDEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEmpleadoActionPerformed

    private void NominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NominaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NominaActionPerformed

    private void TelefonoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelefonoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelefonoEmpleadoActionPerformed

    private void CorreoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CorreoEmpleadoActionPerformed

    private void NombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreEmpleadoActionPerformed

    private void ProyectosRealizadosEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProyectosRealizadosEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProyectosRealizadosEmpleadosActionPerformed

    private void ProyectosRealizadossCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProyectosRealizadossCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProyectosRealizadossCheckActionPerformed

    private void GuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarEmpleadoActionPerformed

    private void MostrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarEmpleadoActionPerformed

    private void NuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NuevoEmpleadoActionPerformed

    private void EliminarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarEmpleadoActionPerformed

    private void JefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JefeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JefeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VENTANA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VENTANA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VENTANA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VENTANA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VENTANA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AporteFinCheck;
    private javax.swing.JTextField AporteFinanciero;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JPanel Cliente;
    private javax.swing.JTextField CodigoProyecto;
    private javax.swing.JTextField Correo;
    private javax.swing.JTextField CorreoEmpleado;
    private javax.swing.JButton EliminarCliente;
    private javax.swing.JButton EliminarEmpleado;
    private javax.swing.JButton EliminarProyecto;
    private javax.swing.JPanel Empleado;
    private javax.swing.JButton GuardarCliente;
    private javax.swing.JButton GuardarEmpleado;
    private javax.swing.JButton GuardarProyecto;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField IDEmpleado;
    private javax.swing.JCheckBox Jefe;
    private javax.swing.JButton MostarCliente;
    private javax.swing.JButton MostrarEmpleado;
    private javax.swing.JButton MostrarProyecto;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField NombreEmpleado;
    private javax.swing.JTextField NombreProyecto;
    private javax.swing.JTextField Nomina;
    private javax.swing.JButton NuevoCliente;
    private javax.swing.JButton NuevoEmpleado;
    private javax.swing.JButton NuevoProyecto;
    private javax.swing.JLabel PintarNombreUsuario;
    private javax.swing.JPanel Proyecto;
    private javax.swing.JTextField ProyectosRealizadosEmpleados;
    private javax.swing.JCheckBox ProyectosRealizadossCheck;
    private javax.swing.JRadioButton RadioButtonEmpresa;
    private javax.swing.JRadioButton RadioButtonPersona;
    private javax.swing.JTextField Telefono;
    private javax.swing.JTextField TelefonoEmpleado;
    private javax.swing.JTextField Tipo;
    private javax.swing.JTextField TipoProyecto;
    private javax.swing.JButton botonCliente;
    private javax.swing.JButton botonEmpleado;
    private javax.swing.JButton botonProyecto;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField15;
    // End of variables declaration//GEN-END:variables
}
